# State-only migration (#841). Media's file fields moved from FileField /
# ProcessedImageField to the ScopedFileField / ScopedProcessedImageField
# subclasses, whose FieldFile scopes a save=True write to its own column instead
# of replaying the whole row. Only the Python class changed, so every operation
# below is a no-op at the SQL level -- confirmed with `manage.py sqlmigrate files 0035`.

# Generated by Django 5.2.17 on 2026-09-12 14:06

from django.db import migrations

import files.models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0034_relative_hls_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media_file",
            field=files.models.ScopedFileField(
                max_length=500, upload_to=files.models.original_media_file_path, verbose_name="media file"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="poster",
            field=files.models.ScopedProcessedImageField(
                blank=True, max_length=500, upload_to=files.models.original_thumbnail_file_path
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="sprites",
            field=files.models.ScopedFileField(
                blank=True, max_length=500, upload_to=files.models.original_thumbnail_file_path
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="thumbnail",
            field=files.models.ScopedProcessedImageField(
                blank=True, max_length=500, upload_to=files.models.original_thumbnail_file_path
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_poster",
            field=files.models.ScopedProcessedImageField(
                blank=True,
                help_text="Image will appear as poster",
                max_length=500,
                upload_to=files.models.original_thumbnail_file_path,
                verbose_name="Upload image",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_thumbnail",
            field=files.models.ScopedProcessedImageField(
                blank=True, max_length=500, upload_to=files.models.original_thumbnail_file_path
            ),
        ),
    ]
